# Generated by Django 3.0.8 on 2020-07-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Just',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
