# Generated by Django 3.0.8 on 2020-07-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_just'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.BooleanField(default=False)),
            ],
        ),
    ]
