# Generated by Django 3.0.8 on 2020-07-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_upstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
